apiVersion: v1
kind: Service
metadata:
  name: lfh-all
  labels:
    app: lfh-all
spec:
  ports:
    - port: 9000
      name: kafdrop-port
      protocol: TCP
      nodePort: 30000
    - name: lfh-port
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31000
    - name: lfh-hl7-port
      protocol: TCP
      port: 2575
      targetPort: 2575
      nodePort: 32000
  selector:
    app: lfh-all
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: lfh-all
spec:
  selector:
    matchLabels:
      app: lfh-all
  template:
    metadata:
      labels:
        app: lfh-all
    spec:
      containers:
        - name: zoo1
          image: docker.io/zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zoo1
        - name: kafka
          image: docker.io/wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: '9092'
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 'localhost'
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: localhost:2181
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_CREATE_TOPICS
              value: sample.topic:1:1
        - name: kafdrop
          image: docker.io/obsidiandynamics/kafdrop
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: 'localhost:9092'
            - name: JVM_OPTS
              value: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
        - name: nats
          image: 'docker.io/nats:2.1.7'
          ports:
            - containerPort: 4222
              protocol: TCP
            - containerPort: 8222
              protocol: TCP
            - containerPort: 6222
              protocol: TCP
        - name: orthanc
          image: 'docker.io/linuxforhealth/orthanc:1.7.2'
          ports:
            - containerPort: 8042
              protocol: TCP
        - name: lfh
          image: 'docker.io/atclark/lfh:latest'
          ports:
            - containerPort: 8081