version: "3.7"
services:
  lfh:
    image: ${LFH_CONNECT_IMAGE}
    restart: "always"
    environment:
      LFH_CONNECT_DATASTORE_URI: "{{lfh.connect.datastore.host}}:<topicName>?brokers=kafka:9092"
      LFH_CONNECT_MESSAGING_URI: "nats:lfh-events?servers=nats-server:4222"
      LFH_CONNECT_MESSAGING_SUBSCRIBE_HOSTS: "nats-server:4222"
      LFH_CONNECT_ORTHANC_SERVER_URI: "http://orthanc:{{lfh.connect.orthanc_server.port}}/instances"
    ports:
      - ${LFH_CONNECT_MLLP_PORT}:${LFH_CONNECT_MLLP_PORT}
      - ${LFH_CONNECT_REST_PORT}:${LFH_CONNECT_REST_PORT}
      - ${LFH_CONNECT_HTTP_PORT}:${LFH_CONNECT_HTTP_PORT}
    depends_on:
      - "kafka"
      - "nats-server"
